name: "Enhancement Request"
description: "Submit a request to enhance or improve an existing feature in the Swarmauri SDK."
title: "[Enhancement Request]: "
labels: ["enhancement", "change request"]

body:
  - type: input
    id: feature_name
    attributes:
      label: "Feature/Enhancement Name"
      description: "Provide a short name for the feature or enhancement"
      placeholder: "e.g., Improve implementation logic"
    validations:
      required: true
      
  - type: textarea
    id: enhancement_description
    attributes:
      label: "Enhancement Description"
      description: "A clear and concise description of the enhancement you're requesting, including any background context."
      placeholder: "Describe the enhancement in detail."
    validations:
      required: true
      
  - type: textarea
    id: motivation
    attributes:
      label: "Motivation"
      description: "Explain why this enhancement is necessary or how it will benefit the SDK. What problem does it solve or what improvement does it offer?"
      placeholder: "Why do you need this enhancement?"
    validations:
      required: true
      
  - type: textarea
    id: potential_solutions
    attributes:
      label: "Potential Solutions"
      description: "Provide any suggestions for how the enhancement could be implemented, if applicable."
      placeholder: "Possible implementation or approach."
    validations:
      required: false

  - type: textarea
    id: additional_context
    attributes:
      label: "Additional Context (optional)"
      description: "Include any other context, screenshots, or relevant information about the enhancement."
      placeholder: "Any additional information."
    validations:
      required: false

  - type: dropdown
    id: impact_area
    attributes:
      label: "Affected Areas"
      description: "Select the area of the SDK that may be impacted by this enhancement."
      options:
        - "Core"
        - "Standard/Base"
        - "Standard/Concrete"
        - "Community"
        - "Experimental"

  - type: dropdown
    id: priority
    attributes:
      label: "Priority"
      description: "What is the priority level of this enhancement?"
      options:
        - "Low"
        - "Medium"
        - "High"
        - "Critical"
    validations:
      required: true
