name: "Refactoring Request "
description: "Submit a change request related to refactoring internal APIs or components."
title: "[Refactoring Request]: "
labels: ["refactoring", "core"]
body:
  - type: input
    id: component_name
    attributes:
      label: "Affected Component"
      description: "Provide the file name(s) of the affected module(s)."
      placeholder: "e.g., standard/concrete/Vector.py"
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: "Motivation"
      description: "Explain why this refactoring request is necessary and how it will improve the codebase. What issues or inefficiencies does it address?"
      placeholder: "Why is this refactor needed?"
    validations:
      required: true

  - type: textarea
    id: potential_solutions
    attributes:
      label: "Potential Refactoring Approach"
      description: "Provide any suggestions for how the code should be refactored, if applicable."
      placeholder: "Possible refactoring approach or solution."
    validations:
      required: false

  - type: input
    id: additional_context
    attributes:
      label: "Additional Context (optional)"
      description: "Include any additional context, screenshots, supporting documentation, or relevant information related to the refactoring."
      placeholder: "Any additional information."
    validations:
      required: false

  - type: checkboxes
    id: impact_area
    attributes:
      label: "Affected Areas"
      description: "Select the areas of the codebase that may be impacted by this refactoring."
      options:
        - label: "Core"
        - label: "Standard/Base"
        - label: "Standard/Concrete"
        - label: "Community"
        - label: "Experimental"

  - type: dropdown
    id: priority
    attributes:
      label: "Priority"
      description: "What is the priority level of this refactoring request?"
      options:
        - "Low"
        - "Medium"
        - "High"
        - "Critical"
    validations:
      required: true
