name: "Technical Debt "
description: "For reporting or tracking areas of the code that need improvement or refactoring due to previous shortcuts."
title: "[Technical Debt]: "
labels: ["technical-debt"]
body:
  - type: input
    id: feature_name
    attributes:
      label: "Affected Component"
      description: "Provide the file name(s) of the affected module(s)."
      placeholder: "e.g., standard/concrete/Vector.py"
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: "Motivation"
      description: "Explain why this technical debt needs to be addressed or how it will benefit the project. What problem does it solve?"
      placeholder: "Why is this improvement necessary?"
    validations:
      required: true

  - type: textarea
    id: potential_solutions
    attributes:
      label: "Potential Solutions"
      description: "Provide any suggestions for how this technical debt could be resolved or how the code can be improved."
      placeholder: "Possible refactoring approach or solution."
    validations:
      required: false

  - type: input
    id: additional_context
    attributes:
      label: "Additional Context (optional)"
      description: "Include any other context, screenshots, or supporting documentation that provides more detail about the issue."
      placeholder: "Any additional information."
    validations:
      required: false

  - type: checkboxes
    id: impact_area
    attributes:
      label: "Affected Areas"
      description: "Select the areas of the codebase that may be impacted by this refactoring."
      options:
        - label: "Core"
        - label: "Standard/Base"
        - label: "Standard/Concrete"
        - label: "Community"
        - label: "Experimental"
