name: "Test Case Failure "
description: "Report issues related to test case failures, including potential causes and solutions."
title: "[Test Case Failure]: "
labels: ["test case failure"]
body:
  - type: input
    id: test_case_name
    attributes:
      label: "Test Case"
      description: "Provide the file name and test case name of the affected test case."
      placeholder: "e.g., tests/vectors/Vector_test.py"
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: "Pytest Logs"
      description: "Provide the pytest logs outputted"
      placeholder: "tests/llms/ShuttleAIToolModel_test.py::test_agent_exec 
      label: "Logs"
      description: "Provide relevant logs"
      placeholder: "FAILED tests/parsers/TextBlobNounParser_test.py::test_parse - LookupError: "

    validations:
      required: true

  - type: textarea
    id: root_cause
    attributes:
      label: "Root Cause"
      description: "Explain why the test case is likely failing."
      placeholder: "The build is likely failing due to..."
    validations:
      required: true

  - type: textarea
    id: potential_solutions
    attributes:
      label: "Potential Solutions"
      description: "Provide any suggestions for how the issue could be fixed, if applicable."
      placeholder: "Possible solution..."
    validations:
      required: false

  - type: textarea
    id: additional_context
    attributes:
      label: "Additional Context (optional)"
      description: "Include any other context, screenshots, supporting documentation, or relevant information about the test case."
      placeholder: "Any additional information."
    validations:
      required: false

  - type: dropdown
    id: test_case_type
    attributes:
      label: "Type of Test Case"
      description: "What type of test case is this?"
      options:
        - "Unit"
        - "Integration"
        - "Acceptance"
    validations:
      required: true
