name: "Build Failure"
description: "Related to build failure"
title: "[Build Failure]:  "
labels: ["build-failure"]
body:
  - type: textarea
    id: root_cause
    attributes:
      label: "Root Cause"
      description: "Explain why the build is likely to fail."
      placeholder: "The build is likely failing due to..."
    validations:
      required: true
      
  - type: input
    id: test_case_name
    attributes:
      label: "Test Case"
      description: "Provide the file name and test case name of the affected test case."
      placeholder: "e.g., tests/vectors/Vector_test.py"
    validations:
      required: false
      
      
  - type: textarea
    id: potential_solutions
    attributes:
      label: "Potential Solutions"
      description: "Provide any suggestions for how the feature could be implemented, if applicable."
      placeholder: "Possible solution."
    validations:
      required: false

  - type: input
    id: additional_context
    attributes:
      label: "Additional Context (optional)"
      description: "Include any other context, screenshots, supporting documentation, or relevant information about the feature."
      placeholder: "Any additional information."
    validations:
      required: false

  - type: checkboxes
    id: impact_area
    attributes:
      label: "Affected Areas"
      description: "Select the areas of the SDK that may be impacted by this feature."
      options:
        - label: "Core"
        - label: "Standard/Base"
        - label: "Standard/Concrete"
        - label: "Community"
        - label: "Experimental"

  - type: dropdown
    id: priority
    attributes:
      label: "Priority"
      description: "What is the priority level of this feature?"
      options:
        - "Low"
        - "Medium"
        - "High"
        - "Critical"
    validations:
      required: true
 
