name: "Technical Debt"
description: "For reporting or tracking areas of the code that need improvement or refactoring due to previous shortcuts. It’s about fixing things like overly complex code, poor design decisions, or deprecated technologies that could slow down development or introduce future bugs."
title: "[Technical Debt]:  "
body:
  - type: input
    id: feature_name
    attributes:
      label: "Affected component"
      description: "Provide the file name(s) of the affected model(s)."
      placeholder: "e.g., standard/concrete/Vector.py"
    validations:
      required: true
      
  - type: textarea
    id: motivation
    attributes:
      label: "Motivation"
      description: "Explain why this change request is necessary or how it will benefit the SDK. What problem does it solve?"
      placeholder: "Why do you need this feature?"
    validations:
      required: true
      
  - type: textarea
    id: potential_solutions
    attributes:
      label: "Potential Solutions"
      description: "Provide any suggestions for how the feature could be implemented, if applicable."
      placeholder: "Possible implementation or approach."
    validations:
      required: false

  - type: input
    id: additional_context
    attributes:
      label: "Additional Context (optional)"
      description: "Include any other context, screenshots, supporting documentation, or relevant information about the feature."
      placeholder: "Any additional information."
    validations:
      required: false

  - type: checkboxes
    id: impact_area
    attributes:
      label: "Affected Areas"
      description: "Select the areas of the SDK that may be impacted by this feature."
      options:
        - label: "Core"
        - label: "Standard/Base"
        - label: "Standard/Concrete"
        - label: "Community"
        - label: "Experimental"

  - type: dropdown
    id: priority
    attributes:
      label: "Priority"
      description: "What is the priority level of this feature?"
      options:
        - "Low"
        - "Medium"
        - "High"
        - "Critical"
    validations:
      required: true
      
